version: '3.8'

services:
  bot:
    build: .
    container_name: test_telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./testbot.db:/app/testbot.db
    command: python bot.py

  admin_app:
    build: .
    container_name: test_bot_admin
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./testbot.db:/app/testbot.db
    command: uvicorn admin_app:app --host 0.0.0.0 --port 8000

